CREATE TABLE app_state(id integer PRIMARY KEY CHECK(id=1), revision integer NOT NULL DEFAULT 1, data jsonb NOT NULL);
CREATE TABLE admin_account(id integer PRIMARY KEY CHECK(id=1), password_hash text NOT NULL, salt text NOT NULL);
CREATE TABLE customer_accounts(id varchar(191) PRIMARY KEY, email varchar(254) NOT NULL UNIQUE, name varchar(191) NOT NULL, phone varchar(32) NOT NULL, password_hash text, salt text, created_at timestamptz NOT NULL DEFAULT now(), firebase_uid varchar(191) UNIQUE);
CREATE TABLE sessions(token varchar(191) PRIMARY KEY, role varchar(20) NOT NULL CHECK(role IN ('admin','guest','customer')), expires_at timestamptz NOT NULL, customer_id varchar(191) REFERENCES customer_accounts(id), firebase_uid varchar(191));
CREATE TABLE merchants(id varchar(191) PRIMARY KEY, kind varchar(20) NOT NULL CHECK(kind='restaurants'), data jsonb NOT NULL);
CREATE TABLE categories(id varchar(191) PRIMARY KEY, merchant_id varchar(191) NOT NULL REFERENCES merchants(id), data jsonb NOT NULL, UNIQUE(id,merchant_id));
CREATE TABLE products(id varchar(191) PRIMARY KEY, merchant_id varchar(191) NOT NULL, category_id varchar(191) NOT NULL, data jsonb NOT NULL, FOREIGN KEY(category_id,merchant_id) REFERENCES categories(id,merchant_id));
CREATE INDEX products_merchant_idx ON products(merchant_id);
CREATE INDEX categories_merchant_idx ON categories(merchant_id);
CREATE TABLE departments(id varchar(191) PRIMARY KEY,data jsonb NOT NULL);
CREATE TABLE customers(id varchar(191) PRIMARY KEY,data jsonb NOT NULL);
CREATE TABLE drivers(id varchar(191) PRIMARY KEY,data jsonb NOT NULL);
CREATE TABLE orders(id varchar(191) PRIMARY KEY,data jsonb NOT NULL,request_id text GENERATED ALWAYS AS (data->>'requestId') STORED,client_session_id text GENERATED ALWAYS AS (data->>'clientSessionId') STORED,order_date text GENERATED ALWAYS AS (data->>'date') STORED);
CREATE UNIQUE INDEX orders_request_idx ON orders(request_id);
CREATE INDEX orders_session_idx ON orders(client_session_id);
CREATE INDEX orders_date_idx ON orders(order_date);
CREATE TABLE notifications(id varchar(191) PRIMARY KEY,data jsonb NOT NULL);
CREATE TABLE seed_history(name varchar(191) PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE admin_login_limits(id varchar(100) PRIMARY KEY,attempts integer NOT NULL,started_at bigint NOT NULL);
