import {readFile} from 'node:fs/promises';
import ts from 'typescript';
import test from 'node:test';
import assert from 'node:assert/strict';
const modules=new Map();
async function load(path){if(modules.has(path))return modules.get(path);let source=await readFile(new URL('../'+path,import.meta.url),'utf8');source=source.replace("'../../../lib/order-workflow.ts'",JSON.stringify(new URL('../lib/order-workflow.ts',import.meta.url).href));const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;const imported=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));modules.set(path,imported);return imported;}
const {initialState}=await load('features/admin/data/demo.ts');const {metrics,inPeriod,chartData}=await load('features/admin/services/metrics.ts');const {changeStatus}=await load('features/admin/services/orders.ts');
test('demo seed includes required catalog and roles',()=>{const s=initialState();assert.equal(s.catalog.products.length,30);assert.equal(s.catalog.restaurants.length,5);assert.equal(s.catalog.drivers.length,5);assert.ok(s.catalog.categories.every(c=>c.merchantId));assert.ok(s.catalog.customers.length>=5);assert.ok(s.orders.length>20);});
test('KPI revenue excludes cancelled and ongoing orders',()=>{const s=initialState();const order=s.orders[0];s.orders=[{...order,total:25,status:'DELIVERED'},{...order,total:100,status:'CANCELLED'},{...order,total:90,status:'PENDING'}];assert.equal(metrics(s).revenue,25);assert.equal(metrics(s).orders,3);});
test('period counts are nested and chart totals reconcile',()=>{const s=initialState(),m=metrics(s);assert.ok(m.today<=m.week&&m.week<=m.month&&m.month<=m.orders);for(const days of [7,30,90]){const series=chartData(s.orders,days);assert.equal(series.reduce((a,b)=>a+b.Commandes,0),s.orders.filter(o=>inPeriod(o,days)).length);assert.equal(series.reduce((a,b)=>a+b.Revenus,0),s.orders.filter(o=>inPeriod(o,days)&&o.status==='DELIVERED').reduce((a,b)=>a+b.total,0));}});
test('status cannot skip steps or reopen terminal orders',()=>{const o=initialState().orders[0];assert.throws(()=>changeStatus({...o,status:'PENDING'},'DELIVERED'));assert.throws(()=>changeStatus({...o,status:'CANCELLED'},'PENDING'));assert.equal(changeStatus({...o,status:'PENDING'},'CONFIRMED').status,'CONFIRMED');});
test('simplified workflow advances without assigning a driver',()=>{const o={...initialState().orders[0],driver:''};assert.equal(changeStatus({...o,status:'CONFIRMED'},'ON_THE_WAY').status,'ON_THE_WAY');assert.throws(()=>changeStatus({...o,status:'PENDING'},'ON_THE_WAY'));assert.throws(()=>changeStatus({...o,status:'CONFIRMED'},'PREPARING'));});
test('delivery completes without driver and delivered status is terminal',()=>{const order={...initialState().orders[0],status:'ON_THE_WAY',driver:''};assert.equal(changeStatus(order,'DELIVERED').status,'DELIVERED');assert.throws(()=>changeStatus({...order,status:'DELIVERED'},'CANCELLED'));});
