'use client';
import {t,useLanguage} from "@/lib/i18n/react";

import {ArrowUpRight,Users,ShoppingBag,Wallet,UtensilsCrossed,LayoutGrid,Package,Bike,ArrowRight} from 'lucide-react';
import {type DemoState,money} from '../data/demo';
import {metrics,chartData,inPeriod} from '../services/metrics';
import {RevenueChart} from '../components/charts';
import {Avatar,Badge} from '../components/common';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
export function Dashboard({state,days,go,openOrder}:{state:DemoState;days:number;go:(page:string)=>void;openOrder:(id:string)=>void}){
 useLanguage();

 const m=metrics(state);const periodOrders=state.orders.filter(o=>inPeriod(o,days));const revenue=periodOrders.filter(o=>o.status==='DELIVERED').reduce((s,o)=>s+o.total,0);const delivered=periodOrders.filter(o=>o.status==='DELIVERED').length;const percent=Math.round(delivered/Math.max(1,periodOrders.length)*100);
 return <><div className="kpis">{t([{name:'Chiffre des commandes',value:money(m.revenue),note:'Total des commandes livrées',icon:Wallet,cls:'violet'},{name:'Total commandes',value:m.orders,note:`${m.today} aujourd’hui`,icon:ShoppingBag,cls:'blue'},{name:'Total utilisateurs',value:m.users,note:'Clients, livreurs et administrateur',icon:Users,cls:'orange'},{name:'Livreurs actifs',value:`${m.active} / ${state.catalog.drivers.length}`,note:`${m.available} disponibles maintenant`,icon:Bike,cls:'green'}].map(k=><section className="kpi" key={k.name}><div className="kpi-top"><span>{t(k.name)}</span><span className={'icon-tile '+k.cls}><k.icon size={19}/></span></div><strong>{t(k.value)}</strong><small>{t(k.note)}</small></section>))}</div>
 <div className="inventory-strip">{t([{name:'Restaurants',v:m.restaurants,icon:UtensilsCrossed,page:'restaurants'},{name:'Rayons accueil',v:m.departments,icon:LayoutGrid,page:'departments'},{name:'Produits',v:m.products,icon:Package,page:'products'}].map(k=><button key={k.name} onClick={()=>go(k.page)}><k.icon size={20}/><span>{t(k.name)}</span><strong>{t(k.v)}</strong><ArrowUpRight size={16}/></button>))}<div><span>{t("Commandes")}</span><b>{t(m.today)} <small>{t("aujourd’hui")}</small></b><b>{t(m.week)} <small>{t("cette semaine")}</small></b><b>{t(m.month)} <small>{t("ce mois")}</small></b></div></div>
 <div className="chart-grid"><section className="panel"><div className="panel-heading"><div><h2>{t("Vue d’ensemble des revenus")}</h2><p>{t("Montants encaissés à la livraison")}</p></div><span className="legend"><i/>{t(" Revenus")}</span></div><div className="chart-total">{t(money(revenue))} <span>{t("sur les ")}{t(days)}{t(" derniers jours")}</span></div><RevenueChart data={chartData(state.orders,days)}/></section><section className="panel performance"><div className="panel-heading"><h2>{t("Commandes")}</h2><ShoppingBag size={18}/></div><div className="donut" style={{background:`conic-gradient(#7772ed 0 ${percent}%, #efedf9 ${percent}% 100%)`}}><div><strong>{t(periodOrders.length)}</strong><span>{t("commandes")}</span></div></div><div className="donut-legend"><span><i className="purple-dot"/>{t("Livrées ")}<b>{t(delivered)}</b></span><span><i className="orange-dot"/>{t("En cours ")}<b>{t(periodOrders.filter(o=>!['DELIVERED','CANCELLED'].includes(o.status)).length)}</b></span><span><i className="gray-dot"/>{t("Annulées ")}<b>{t(periodOrders.filter(o=>o.status==='CANCELLED').length)}</b></span></div><p className="success-note">{t(percent)}{t(" % de commandes livrées")}</p></section></div>
 <div className="bottom-grid"><section className="panel order-panel"><div className="panel-heading"><div><h2>{t("Commandes récentes")}</h2><p>{t("Les dernières activités de votre plateforme")}</p></div><button className="text-button" onClick={()=>go('orders')}>{t("Tout voir ")}<ArrowRight size={16}/></button></div><Table><TableHeader><TableRow>{t(['Commande','Client / Commerce','Montant','Statut',''].map((h,i)=><TableHead key={i}>{t(h)}</TableHead>))}</TableRow></TableHeader><TableBody>{t(state.orders.slice(0,5).map(o=><TableRow key={o.id}><TableCell><button className="order-link" onClick={()=>openOrder(o.id)}>#{t(o.id.slice(4))}</button><small>{t(new Date(o.date).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}))}</small></TableCell><TableCell><span className="person"><Avatar name={o.customer}/><span>{t(o.customer)}<small>{t(o.merchant)}</small></span></span></TableCell><TableCell>{t(money(o.total))}</TableCell><TableCell><Badge status={o.status}/></TableCell><TableCell><button className="icon-button" aria-label={t('Ouvrir '+o.id)} onClick={()=>openOrder(o.id)}><ArrowUpRight size={17}/></button></TableCell></TableRow>))}</TableBody></Table></section><section className="panel"><div className="panel-heading"><h2>{t("Livreurs disponibles")}</h2><span className="count">{t(m.available)}</span></div><p className="muted">{t("Prêts à prendre la route")}</p>{t(state.catalog.drivers.filter(d=>d.status==='AVAILABLE').map(d=><div className="driver-row" key={d.id}><Avatar name={d.name}/><div><b>{t(d.name)}</b><small>{t(d.detail)} · {t(d.vehicle)}</small></div><span className="online-dot"/></div>))}<button className="outline-button full" onClick={()=>go('drivers')}>{t("Gérer les livreurs ")}<ArrowRight size={16}/></button><div className="dispatch-note"><Bike size={22}/><div><b>{t("Une livraison à assigner ?")}</b><p>{t("Retrouvez vos commandes en attente dans l’espace livraisons.")}</p><button className="text-button" onClick={()=>go('deliveries')}>{t("Voir les livraisons →")}</button></div></div></section></div></>;
}
