'use client';
import {t,useLanguage} from "@/lib/i18n/react";

import {useState} from 'react';
import {type DemoState,money} from '../data/demo';
import {chartData,inPeriod} from '../services/metrics';
import {RevenueChart,SmallBars} from '../components/charts';
import {Choice,Avatar,Badge} from '../components/common';
export function Statistics({state,days}:{state:DemoState;days:number}){
 useLanguage();
const [driver,setDriver]=useState('all');const [metric,setMetric]=useState('Commandes');const orders=state.orders.filter(o=>driver==='all'||o.driver===driver);const period=orders.filter(o=>inPeriod(o,days));const completed=period.filter(o=>o.status==='DELIVERED');const revenue=completed.reduce((s,o)=>s+o.total,0);const cancelled=period.filter(o=>o.status==='CANCELLED').length;const ranking=state.catalog.restaurants.map(m=>({name:m.name,value:period.filter(o=>o.merchant===m.name).length})).sort((a,b)=>b.value-a.value).slice(0,5);return <><div className="stats-filter"><Choice label={t("Filtrer par livreur")} value={driver} onChange={setDriver} options={[{value:'all',label:'Tous les livreurs'},...state.catalog.drivers.map(d=>({value:d.name,label:d.name}))]}/><span className="muted">{t(days)}{t(" derniers jours · ")}{t(period.length)}{t(" commandes")}</span></div><div className="kpis">{t([{name:'Commandes livrées',value:completed.length},{name:'Revenus encaissés',value:money(revenue)},{name:'Panier moyen livré',value:money(revenue/Math.max(1,completed.length))},{name:'Taux d’annulation',value:(cancelled/Math.max(1,period.length)*100).toFixed(1)+' %'}].map(k=><section className="kpi" key={k.name}><span className="muted">{t(k.name)}</span><strong>{t(k.value)}</strong><small>{t("Sur la période sélectionnée")}</small></section>))}</div><div className="chart-grid statistics-grid"><section className="panel"><div className="panel-heading"><h2>{t("Évolution de l’activité")}</h2><Choice label={t("Indicateur du graphique")} value={metric} onChange={setMetric} options={[{value:'Commandes',label:'Commandes'},{value:'Revenus',label:'Revenus'}]}/></div><RevenueChart data={chartData(orders,days)} metric={metric as 'Commandes'|'Revenus'}/></section><section className="panel"><h2>{t("Activité du catalogue")}</h2><SmallBars data={[{name:'Restaurants actifs',value:state.catalog.restaurants.filter(m=>m.status==='ACTIVE').length},{name:'Rayons accueil actifs',value:state.catalog.departments.filter(d=>d.status==='ACTIVE').length}]}/></section></div><div className="bottom-grid"><section className="panel"><h2>{t("Commerces les plus commandés")}</h2>{t(ranking.map((m,i)=><div className="ranking" key={m.name}><span className="rank">0{t(i+1)}</span><Avatar name={m.name}/><b>{t(m.name)}</b><div className="rank-bar"><span style={{width:Math.max(1,m.value/Math.max(1,ranking[0].value)*100)+'%'}}/></div><span>{t(m.value)}{t(" commandes")}</span></div>))}</section><section className="panel"><h2>{t("Activité des livreurs")}</h2>{t(state.catalog.drivers.filter(d=>driver==='all'||d.name===driver).map(d=><div className="driver-row" key={d.id}><Avatar name={d.name}/><div><b>{t(d.name)}</b><small>{t(period.filter(o=>o.driver===d.name&&o.status==='DELIVERED').length)}{t(" livraisons · Note ")}{t(d.value.toFixed(1))}/5</small></div><Badge status={d.status}/></div>))}</section></div></>}
