'use client';
import {localizeState} from '@/lib/i18n/catalog';
import {useMemo,useSyncExternalStore} from 'react';
import {type DemoState} from '../../admin/data/demo';
import {type CheckoutInput} from './checkout';
const empty:DemoState={catalog:{restaurants:[],products:[],categories:[],departments:[],customers:[],drivers:[]},orders:[],notifications:[],settings:{name:'Hadhri Delivery',email:'',fee:4,loyaltyEnabled:true}};
let cached=empty,revision=0,loading=false,timer:ReturnType<typeof setInterval>|undefined;
const listeners=new Set<()=>void>();
export async function api<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch('/api/v1'+path+(path.includes('?')?'&':'?')+'lang=fr',{...options,headers:{'Content-Type':'application/json',...options.headers}});const value=await response.json();if(!response.ok)throw new Error((value as {error?:string}).error||'Connexion impossible');return value as T;}
function notify(){listeners.forEach(fn=>fn())}
export async function refresh(){if(loading)return;loading=true;try{const result=await api<{state:DemoState;revision:number}>(location.pathname.startsWith('/admin')?'/admin/state':'/state');cached=result.state;revision=result.revision;notify();window.dispatchEvent(new CustomEvent('api-status',{detail:''}));}catch(e){window.dispatchEvent(new CustomEvent('api-status',{detail:(e as Error).message}))}finally{loading=false}}
function subscribe(fn:()=>void){listeners.add(fn);void refresh();if(!timer){timer=setInterval(()=>{if(!document.hidden)void refresh()},15000);const immediate=()=>{void refresh()};try{window.addEventListener('focus',immediate);window.addEventListener('online',immediate);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh()})}catch{}}return()=>{listeners.delete(fn);if(!listeners.size){clearInterval(timer);timer=undefined}}}
export async function writeState(next:DemoState){const changes:{kind:string;id?:string;value:unknown}[]=[];for(const kind of [...Object.keys(cached.catalog),'orders','notifications']){const before=cached.catalog[kind]||cached[kind as 'orders'|'notifications'];const after=next.catalog[kind]||next[kind as 'orders'|'notifications'];for(const row of after)if(JSON.stringify(row)!==JSON.stringify(before.find(p=>p.id===row.id)))changes.push({kind,id:row.id,value:row});for(const row of before)if(!after.some(p=>p.id===row.id))changes.push({kind,id:row.id,value:null})}if(JSON.stringify(cached.settings)!==JSON.stringify(next.settings))changes.push({kind:'settings',value:next.settings});try{if(changes.length)await api('/admin/state',{method:'PATCH',body:JSON.stringify({revision,changes})});await refresh()}catch(e){await refresh();window.dispatchEvent(new CustomEvent('api-status',{detail:(e as Error).message}));throw e}}
export function useDemoStore(){const state=useSyncExternalStore(subscribe,()=>cached,()=>empty);const localized=useMemo(()=>localizeState(state,'fr'),[state]);return [typeof window!=="undefined"&&window.location.pathname.startsWith("/admin")?state:localized,writeState] as const}
export async function placeLocalOrder(input:CheckoutInput){const orders=await api<DemoState['orders']>('/orders',{method:'POST',body:JSON.stringify(input)});await refresh();return orders}
